apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/redis-enterprise-operator-cert-rhmp.redis: ""
  name: redis-enterprise-operator-cert-rhmp
  namespace: redis
spec:
  channel: production
  installPlanApproval: Automatic
  name: redis-enterprise-operator-cert-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: redis-enterprise-operator.v6.2.10-4
